name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: aptUpdate
      run: sudo apt -y install clang
    - name: aptAlternativeC
      run: sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
    - name: aptAlternativeCXX
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100
    - name: make test
      run: make test
