name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: updateClangC
      run: sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
    - name: updateClangCXX
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
