name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: info
      run: clang++ --version
    - name: testA
      run: make testA
    - name: testM
      run: make testM
    - name: testT
      run: make testT
    - name: testU
      run: make testU
