name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: alpine-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: updateClang
      run: sudo apk add clang make
    - name: testA
      run: make testA
    - name: testM
      run: make testM
    - name: testT
      run: make testT
    - name: testU
      run: make testU
