name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: alpine-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: updateClang
      run: sudo apk add clang make
    - name: make test testA
      run: make test testA
    - name: make test testM
      run: make test testM
    - name: make test testT
      run: make test testT
    - name: make test testU
      run: make test testU
